AppointmentManagerApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using AppointmentManagerApp.Models;


namespace AppointmentManagerApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppointmentManagerApp/ViewComponents/MembershipViewComponent.cs
using AppointmentManagerApp.Models.Membership.ViewModel;
using AppointmentManagerApp.Services.Membership;
using AppointmentManagerApp.Services.User;
using Microsoft.AspNetCore.Mvc;

namespace AppointmentManagerApp.ViewComponents;

[ViewComponent]
public class MembershipViewComponent : ViewComponent
{
    private readonly IMembershipService _membershipService;
    private readonly IUserService _userService;

    public MembershipViewComponent(IMembershipService membershipService,
        IUserService userService)
    {
        _membershipService = membershipService;
        _userService = userService;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var user = await _userService.GetUserAsync();
        var memberships = await _membershipService.GetUserMembership(user.Id);

        var model = new UserMembershipsViewModel();
        model.UserId = user.Id;
        model.Memberships = memberships.Select(x => new MembershipViewModel()
        {
            Type = x.Type,
            Duration = x.Duration,
            StartDate = x.StartDate.ToString("dd.MM.yyyy"),
            EndDate = x.StartDate.AddDays(x.Duration).ToString("dd.MM.yyyy"),
        });

        return View("~/Views/Membership/_UserMemberships.cshtml", model);
    }
}

AppointmentManagerApp/Views/Home/Index.cshtml
@using AppointmentManagerApp.Models.Membership.ViewModel;
@using AppointmentManagerApp.ViewComponents;
@using AppointmentManagerApp.Controllers;
@model IndexModel
@{
    ViewData["Title"] = Model?.AppTitle;
}

@if (!string.IsNullOrEmpty(Model?.ErrorMessage))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @Model.ErrorMessage
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (!string.IsNullOrEmpty(Model?.SuccessMessage))
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @Model.SuccessMessage
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@if (User?.Identity?.IsAuthenticated ?? false)
{
    <p class="m-0" align="left">
        @await Component.InvokeAsync("Membership")
    </p>


    @Html.Partial("~/Views/Membership/_BuyMembership.cshtml", new MembershipViewModel())
}
else
{
    <p class="m-0" align="left">
        Приложение для записи в тренажерный зал. Зарегистрируйтесь или войдите в систему, чтобы получить доступ к функциям.
    </p>
}