AppointmentManagerApp/Controllers/AdminController.cs
using AppointmentManagerApp.Models.Admin.ViewModel;
using AppointmentManagerApp.Models.Auth.Domain;
using AppointmentManagerApp.Models.Auth.Requests;
using AppointmentManagerApp.Models.User.Domain;
using AppointmentManagerApp.Models.User.Requests;
using AppointmentManagerApp.Services.Auth;
using AppointmentManagerApp.Services.User;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AppointmentManagerApp.Controllers;

[Authorize(Roles = nameof(Roles.Admin))]
public class AdminController : Controller
{
    private readonly IAuthService _authService;
    private readonly IUserService _userService;
    private readonly IMapper _mapper;

    public AdminController(IUserService userService, IAuthService authService, IMapper mapper)
    {
        _userService = userService;
        _authService = authService;
        _mapper = mapper;
    }

    public IActionResult Index()
    {
        return View(nameof(Index));
    }

    public async Task<IActionResult> UserManagement(CancellationToken cancellationToken)
    {
        var allUsersTask = _userService.GetUsersListAsync();
        var userRolesTask = _authService.GetUsersRolesListAsync(cancellationToken);

        await Task.WhenAll(allUsersTask, userRolesTask);

        var castedUsers = allUsersTask.Result
            .Select(item => new UserFullInfo()
            { 
                Id = item.Id,
                Email = item.Email,
                FirstName = item.FirstName,
                LastName = item.LastName,
                PhoneNumber = item.PhoneNumber,
                Promocode = item.Promocode,
                Role = userRolesTask.Result.FirstOrDefault(x => x.Id == item.Id)?
                .Claims?.FirstOrDefault()?.Value
            });

        return View(nameof(UserManagement), new UserManagementVm { 
            Users = castedUsers
        });
    }

    [HttpPost]
    public async Task<IActionResult> CreateUser(CreateUserByAdminVm model, CancellationToken cancellationToken)
    {
        var authModel = _mapper.Map<CreateUserByAdminVm, AuthCreateUserRequest>(model);
        var creationResult = await _authService.CreateRandomPasswordUserAsync(authModel, cancellationToken);

        if (!string.IsNullOrEmpty(creationResult.ErrorMessage))
        {
            model.ErrorMessage = $"Не удалось зарегистрировать нового пользователя: {creationResult.ErrorMessage}";
            return View("~/Views/Admin/UserManagement.cshtml", new UserManagementVm() { ErrorMessage = model.ErrorMessage });
        }

        var coreModel = _mapper.Map<CreateUserByAdminVm, CreateUserRequest>(model);
        coreModel.Id = creationResult.UserId;

        await _userService.CreateUserAsync(coreModel, cancellationToken);

        return View("~/Views/Admin/UserManagement.cshtml", new UserManagementVm() { SuccessMessage = "Пользователь успешно зарегистрирован." });
    }
}

AppointmentManagerApp/Controllers/AuthController.cs
using AppointmentManagerApp.Models.Auth.ViewModel;
using AppointmentManagerApp.Services.Auth;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AppointmentManagerApp.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    [AllowAnonymous]
    public IActionResult Login()
    {
        return View(nameof(Login));
    }

    [AllowAnonymous]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(LoginVm model, CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid)
        {
            return View(nameof(Login));
        }

        var loginSuccess = await _authService.LoginAsync(model.Email, model.Password, cancellationToken);
        if(loginSuccess)
            return RedirectToAction("Index", "Home");

        model.IsLoginFailed = true;

        return View(nameof(Login), model);
    }

    [Authorize]
    public async Task<IActionResult> SignOut(CancellationToken cancellationToken)
    {
        await _authService.SignOutAsync(cancellationToken);
        return RedirectToAction("Index", "Home");
    }
}

AppointmentManagerApp/Controllers/ScheduleController.cs
using AppointmentManagerApp.Models;
using AppointmentManagerApp.Models.Schedule;
using AppointmentManagerApp.Services.Auth;
using AppointmentManagerApp.Services.Schedule;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Claims;
using Microsoft.IdentityModel.JsonWebTokens;

namespace AppointmentManagerApp.Controllers;

public class ScheduleController : Controller
{
	private readonly IScheduleService _scheduleService;

	public ScheduleController(IScheduleService scheduleService)
	{
		_scheduleService = scheduleService;
	}

	[Authorize]
	public IActionResult Index()
	{
		var model = new ScheduleModel
		{
			Schedules = _scheduleService.GetSchedulesByCustomerAsync(HttpContext.User.Claims.FirstOrDefault(x => string.Equals(x.Type, ClaimTypes.NameIdentifier, StringComparison.OrdinalIgnoreCase)
				|| string.Equals(x.Type, JwtRegisteredClaimNames.NameId, StringComparison.OrdinalIgnoreCase))?.Value, CancellationToken.None).Result.Schedules?.Select(s => new Schedule
				{
					EndTime = s.EndTime,
					StartTime = s.StartTime,
				}).ToList(),
		};//_authService.GetUserProfileModel(HttpContext.User.Claims);

		return View(nameof(Index), model);
	}


}

AppointmentManagerApp/Controllers/UserController.cs
using AppointmentManagerApp.Models;
using AppointmentManagerApp.Models.Auth.Requests;
using AppointmentManagerApp.Models.Benefit.Requests;
using AppointmentManagerApp.Models.Notification.Requests;
using AppointmentManagerApp.Models.User.Domain;
using AppointmentManagerApp.Models.User.Requests;
using AppointmentManagerApp.Models.User.ViewModel;
using AppointmentManagerApp.Providers.Benefit;
using AppointmentManagerApp.Services.Auth;
using AppointmentManagerApp.Services.Notification;
using AppointmentManagerApp.Services.User;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AppointmentManagerApp.Models.Notification.Requests;

namespace AppointmentManagerApp.Controllers;

public class UserController : Controller
{
    private readonly IAuthService _authService;
    private readonly IUserService _userService;
    private readonly INotificationService _notificationService;
    private readonly IMapper _mapper;
    private readonly IBenefitProvider _benefitProvider;

    public UserController(IUserService userService, IAuthService authService, IMapper mapper, INotificationService notificationService, IBenefitProvider benefitProvider)
    {
        _userService = userService;
        _authService = authService;
        _mapper = mapper;
        _benefitProvider = benefitProvider;
        _notificationService = notificationService;
    }

    [Authorize]
    public async Task<IActionResult> Index()
    {
        var user = await _userService.GetUserAsync();
        var benefit = await _benefitProvider.GetDiscountBenefitAsync(new GetUserBenefitRequest() { UserId = user.Id, Subscription = 3, TrainingSessions = 0 });
        var model = _mapper.Map<UserBase, UserVm>(user);
        model.Discount = benefit?.BenefitUser;

        return View(nameof(Index), model);
    }

    [AllowAnonymous]
    public IActionResult Create()
    {
        return View(nameof(Create));
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Create(UserVm model, CancellationToken cancellationToken)
    {
        var authModel = _mapper.Map<UserVm, AuthCreateUserRequest>(model);
        var creationResult = await _authService.CreateUserAsync(authModel, cancellationToken);

        if (!string.IsNullOrEmpty(creationResult.ErrorMessage))
        {
            model.ErrorMessage = $"Не удалось зарегистрировать нового пользователя: {creationResult.ErrorMessage}";
            return View(nameof(Create), model);
        }
        //создаем канал уведомлений по почте зарегистрированного пользователя
        var req = new CreateNotificationChannelRequest()
        {
            Adress = authModel.Email,
            UserId = creationResult.UserId,
            ChannelType = 0
        };
        await _notificationService.CreateNotificationChannelAsync(req, cancellationToken);
        var coreModel = _mapper.Map<UserVm, CreateUserRequest>(model);
        coreModel.Id = creationResult.UserId;

        var res = await _userService.CreateUserAsync(coreModel, cancellationToken);

        await _benefitProvider.ApplyRegitrationAsync(new ApplyRegitrationRequest()
        {
            UserId = creationResult.UserId,
            RefCode = coreModel.Promocode,
            UserCode = Guid.NewGuid().ToString()
        }
        );


        return View("~/Views/Home/Index.cshtml", new IndexModel() { SuccessMessage = "Вы успешно зарегистрированы. Теперь вы можете войти." });
    }
}

AppointmentManagerApp/Views/Shared/_Layout.cshtml
@using AppointmentManagerApp.Models.Auth.Domain;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Запись в тренажерный зал</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item px-2">
                                @Html.ActionLink("Расписание", "Index", "Schedule")
                            </li>                             
                        }                                
                        @if (User.IsInRole(nameof(Roles.Admin)))
                        {
                            <li class="nav-item px-2">
                                @Html.ActionLink("Администрирование", "Index", "Admin")
                            </li>                            
                        }
                    </ul>
                    <div class="form-inline">
                        @Html.Partial("_UserProfileMenu")
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @Html.Partial("_ValidationScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentManagerApp/Views/Shared/_UserProfileMenu.cshtml
@using AppointmentManagerApp.Models.Auth.Domain;
@{
}


@if (User?.Identity?.IsAuthenticated ?? false)
{	
	<p class="m-0" align="right">
		@Html.ActionLink(User.Identity.Name, "Index", "User") | @Html.ActionLink("Выйти", "SignOut", "Auth")
	</p>
}
else
{
	<p class="m-0" align="right">
		@Html.ActionLink("Войти", "Login", "Auth") | @Html.ActionLink("Регистрация", "Create", "User")
	</p>
}